require("dotenv").config();

const mongoose = require("mongoose");

const connectDB = require("../config/db");
const Category = require("../models/Category");
const Scheme = require("../models/Scheme");
const UserResponse = require("../models/UserResponse");

const categories = [
  {
    id: "farmer",
    name: "Farmer",
    localName: "किसान",
    localNameKn: "ರೈತ",
    icon: "👨‍🌾",
    schemeCount: 3,
    color: "#1a7a4a",
  },
  {
    id: "woman",
    name: "Woman",
    localName: "महिला",
    localNameKn: "ಮಹಿಳೆ",
    icon: "👩",
    schemeCount: 3,
    color: "#e64b3c",
  },
  {
    id: "senior",
    name: "Senior",
    localName: "बुजुर्ग",
    localNameKn: "ಹಿರಿಯರು",
    icon: "👴",
    schemeCount: 2,
    color: "#f2a51a",
  },
  {
    id: "family",
    name: "Family",
    localName: "परिवार",
    localNameKn: "ಕುಟುಂಬ",
    icon: "🏠",
    schemeCount: 2,
    color: "#2484b8",
  },
  {
    id: "student",
    name: "Student",
    localName: "विद्यार्थी",
    localNameKn: "ವಿದ್ಯಾರ್ಥಿ",
    icon: "🎓",
    schemeCount: 2,
    color: "#6b5dd3",
  },
  {
    id: "business",
    name: "Business",
    localName: "व्यवसाय",
    localNameKn: "ವ್ಯಾಪಾರ",
    icon: "🏪",
    schemeCount: 2,
    color: "#0f8b8d",
  },
];

const schemes = [
  {
    name: "PM-KISAN Samman Nidhi",
    category: "farmer",
    benefits: "Income support for eligible farmer families.",
    eligibility: "Small and marginal farmer families as per government rules.",
    documentsRequired: ["Aadhaar card", "Bank passbook", "Land records"],
    applyLink: "https://pmkisan.gov.in/",
    rules: {
      landSize: ["Below 1 acre", "1-5 acres"],
      annualIncome: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Fasal Bima Yojana",
    category: "farmer",
    benefits: "Crop insurance support against crop loss.",
    eligibility: "Farmers growing notified crops in notified areas.",
    documentsRequired: ["Aadhaar card", "Bank details", "Land records", "Crop details"],
    applyLink: "https://pmfby.gov.in/",
    rules: {
      cropType: ["Rice", "Wheat", "Cotton", "Vegetables", "Other"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Krishi Sinchai Yojana",
    category: "farmer",
    benefits: "Support for irrigation and water-use efficiency.",
    eligibility: "Farmers needing irrigation support.",
    documentsRequired: ["Aadhaar card", "Land records", "Bank details"],
    applyLink: "https://pmksy.gov.in/",
    rules: {
      irrigationAvailable: "No",
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Matru Vandana Yojana",
    category: "woman",
    benefits: "Maternity benefit support for eligible women.",
    eligibility: "Pregnant and lactating mothers as per scheme rules.",
    documentsRequired: ["Aadhaar card", "Bank passbook", "Pregnancy records"],
    applyLink: "https://pmmvy.wcd.gov.in/",
    rules: {
      maritalStatus: ["Married"],
      income: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "Sukanya Samriddhi Yojana",
    category: "woman",
    benefits: "Savings scheme for girl child education and future needs.",
    eligibility: "Girl child below eligible age limit through parent or guardian.",
    documentsRequired: ["Birth certificate", "Guardian ID proof", "Address proof"],
    applyLink: "https://www.indiapost.gov.in/",
    rules: {
      occupation: ["Homemaker", "Worker", "Small business", "Farmer"],
    },
    active: true,
  },
  {
    name: "Udyogini Scheme",
    category: "woman",
    benefits: "Financial assistance for women entrepreneurs.",
    eligibility: "Women starting or running eligible small businesses.",
    documentsRequired: ["Aadhaar card", "Income certificate", "Business plan", "Bank details"],
    applyLink: "https://udyamimitra.in/",
    rules: {
      occupation: ["Small business"],
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "National Scholarship Portal Scholarships",
    category: "student",
    benefits: "Scholarship support for eligible students.",
    eligibility: "Students meeting income, category, education, and state rules.",
    documentsRequired: ["Aadhaar card", "Income certificate", "Caste certificate", "Marks card", "Bank details"],
    applyLink: "https://scholarships.gov.in/",
    rules: {
      annualFamilyIncome: ["Below 1 lakh", "1-3 lakh"],
      educationLevel: ["School", "PUC/12th", "Diploma", "Graduate"],
    },
    active: true,
  },
  {
    name: "Post Matric Scholarship",
    category: "student",
    benefits: "Education fee and maintenance support.",
    eligibility: "Eligible SC/ST/OBC/Minority students as per rules.",
    documentsRequired: ["Caste certificate", "Income certificate", "Marks card", "Bank details"],
    applyLink: "https://scholarships.gov.in/",
    rules: {
      casteCategory: ["OBC", "SC", "ST", "Minority"],
    },
    active: true,
  },
  {
    name: "Indira Gandhi National Old Age Pension Scheme",
    category: "senior",
    benefits: "Monthly pension support for eligible senior citizens.",
    eligibility: "Senior citizens from eligible low-income households.",
    documentsRequired: ["Aadhaar card", "Age proof", "Income certificate", "Bank details"],
    applyLink: "https://nsap.nic.in/",
    rules: {
      age: ["60-69", "70-79", "80+"],
      pensionStatus: ["Not receiving pension"],
    },
    active: true,
  },
  {
    name: "Ayushman Bharat PM-JAY",
    category: "senior",
    benefits: "Health insurance cover for eligible families.",
    eligibility: "Eligible households under PM-JAY criteria.",
    documentsRequired: ["Aadhaar card", "Ration card", "Mobile number"],
    applyLink: "https://pmjay.gov.in/",
    rules: {
      healthCondition: ["Chronic illness", "Disability", "Needs support"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Awas Yojana",
    category: "family",
    benefits: "Housing support for eligible families.",
    eligibility: "Families without pucca house as per scheme rules.",
    documentsRequired: ["Aadhaar card", "Income certificate", "Address proof", "Bank details"],
    applyLink: "https://pmaymis.gov.in/",
    rules: {
      houseType: ["No house", "Rented house"],
      income: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "National Food Security Act Ration Benefits",
    category: "family",
    benefits: "Subsidized food grains for eligible households.",
    eligibility: "Eligible priority households as identified by state rules.",
    documentsRequired: ["Ration card", "Aadhaar card", "Address proof"],
    applyLink: "https://nfsa.gov.in/",
    rules: {
      income: ["Below 1 lakh", "1-3 lakh"],
      familySize: ["3-4", "5+"],
    },
    active: true,
  },
  {
    name: "PM Mudra Yojana",
    category: "business",
    benefits: "Loan support for micro and small businesses.",
    eligibility: "Non-corporate small business units needing finance.",
    documentsRequired: ["Aadhaar card", "Business proof", "Bank statement", "Quotation or business plan"],
    applyLink: "https://www.mudra.org.in/",
    rules: {
      loanRequired: "Yes",
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "PMEGP",
    category: "business",
    benefits: "Credit-linked subsidy for new micro-enterprises.",
    eligibility: "Eligible applicants starting a new micro-enterprise.",
    documentsRequired: ["Aadhaar card", "Project report", "Education proof", "Caste certificate if applicable"],
    applyLink: "https://www.kviconline.gov.in/pmegpeportal/",
    rules: {
      businessType: ["Shop", "Tailoring", "Food business", "Service", "Other"],
      loanRequired: "Yes",
    },
    active: true,
  },
];

const additionalSchemes = [
  {
    name: "Soil Health Card Scheme",
    category: "farmer",
    benefits: "Soil testing support and crop nutrient guidance for farmers.",
    eligibility: "Farmers who need soil quality and fertilizer recommendations.",
    documentsRequired: ["Aadhaar card", "Land records", "Mobile number"],
    applyLink: "https://soilhealth.dac.gov.in/",
    rules: {
      cropType: ["Rice", "Wheat", "Cotton", "Vegetables", "Other"],
      landSize: ["Below 1 acre", "1-5 acres", "Above 5 acres"],
    },
    active: true,
  },
  {
    name: "Kisan Credit Card",
    category: "farmer",
    benefits: "Credit support for crop cultivation and farm needs.",
    eligibility: "Eligible farmers, tenant farmers, and sharecroppers as per bank rules.",
    documentsRequired: ["Aadhaar card", "Land records", "Bank details", "Photograph"],
    applyLink: "https://www.myscheme.gov.in/schemes/kcc",
    rules: {
      landSize: ["Below 1 acre", "1-5 acres", "Above 5 acres"],
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "Paramparagat Krishi Vikas Yojana",
    category: "farmer",
    benefits: "Support for organic farming and certification.",
    eligibility: "Farmers interested in organic farming clusters.",
    documentsRequired: ["Aadhaar card", "Land records", "Bank details"],
    applyLink: "https://pgsindia-ncof.gov.in/",
    rules: {
      cropType: ["Rice", "Wheat", "Vegetables", "Other"],
    },
    active: true,
  },
  {
    name: "Sub-Mission on Agricultural Mechanization",
    category: "farmer",
    benefits: "Assistance for farm machinery and equipment access.",
    eligibility: "Farmers and farmer groups needing mechanization support.",
    documentsRequired: ["Aadhaar card", "Land records", "Quotation", "Bank details"],
    applyLink: "https://agrimachinery.nic.in/",
    rules: {
      landSize: ["1-5 acres", "Above 5 acres"],
      annualIncome: ["1-3 lakh", "3-6 lakh", "Above 6 lakh"],
    },
    active: true,
  },
  {
    name: "National Mission on Horticulture",
    category: "farmer",
    benefits: "Support for horticulture crops, nurseries, and post-harvest management.",
    eligibility: "Farmers growing fruits, vegetables, flowers, and horticulture crops.",
    documentsRequired: ["Aadhaar card", "Land records", "Crop details", "Bank details"],
    applyLink: "https://midh.gov.in/",
    rules: {
      cropType: ["Vegetables", "Other"],
    },
    active: true,
  },
  {
    name: "Mahila Shakti Kendra",
    category: "woman",
    benefits: "Community support and empowerment services for rural women.",
    eligibility: "Women needing support for welfare services and empowerment programmes.",
    documentsRequired: ["Aadhaar card", "Address proof", "Mobile number"],
    applyLink: "https://wcd.nic.in/",
    rules: {
      occupation: ["Homemaker", "Worker", "Farmer", "Student"],
    },
    active: true,
  },
  {
    name: "One Stop Centre Scheme",
    category: "woman",
    benefits: "Integrated support for women affected by violence.",
    eligibility: "Women needing emergency, legal, medical, or counselling support.",
    documentsRequired: ["Identity proof if available", "Contact details"],
    applyLink: "https://wcd.nic.in/",
    rules: {
      maritalStatus: ["Single", "Married", "Widowed", "Divorced"],
    },
    active: true,
  },
  {
    name: "Working Women Hostel Scheme",
    category: "woman",
    benefits: "Safe and affordable hostel accommodation for working women.",
    eligibility: "Working women and trainees as per scheme rules.",
    documentsRequired: ["Aadhaar card", "Employment proof", "Income proof"],
    applyLink: "https://wcd.nic.in/",
    rules: {
      occupation: ["Worker", "Small business", "Student"],
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "Stand-Up India Scheme for Women",
    category: "woman",
    benefits: "Bank loan support for women entrepreneurs.",
    eligibility: "Women starting greenfield enterprises in eligible sectors.",
    documentsRequired: ["Aadhaar card", "Business plan", "Bank details", "Caste certificate if applicable"],
    applyLink: "https://www.standupmitra.in/",
    rules: {
      occupation: ["Small business"],
      income: ["1-3 lakh", "3-6 lakh", "Above 6 lakh"],
    },
    active: true,
  },
  {
    name: "Beti Bachao Beti Padhao",
    category: "woman",
    benefits: "Awareness and support for girl child education and protection.",
    eligibility: "Families and communities supporting girl child welfare.",
    documentsRequired: ["Aadhaar card", "Birth certificate if applicable"],
    applyLink: "https://wcd.nic.in/bbbp-schemes",
    rules: {
      educationLevel: ["No formal education", "School", "PUC/12th"],
    },
    active: true,
  },
  {
    name: "Indira Gandhi National Widow Pension Scheme",
    category: "woman",
    benefits: "Pension support for eligible widows from low-income households.",
    eligibility: "Widows meeting age and income criteria under NSAP/state rules.",
    documentsRequired: ["Aadhaar card", "Death certificate of spouse", "Income certificate", "Bank details"],
    applyLink: "https://nsap.nic.in/",
    rules: {
      maritalStatus: ["Widowed"],
      income: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "Atal Pension Yojana",
    category: "senior",
    benefits: "Pension savings support for old age security.",
    eligibility: "Eligible subscribers as per pension scheme rules.",
    documentsRequired: ["Aadhaar card", "Bank account", "Mobile number"],
    applyLink: "https://www.npscra.nsdl.co.in/scheme-details.php",
    rules: {
      pensionStatus: ["Not receiving pension"],
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "Rashtriya Vayoshri Yojana",
    category: "senior",
    benefits: "Assistive devices for eligible senior citizens.",
    eligibility: "Senior citizens with age-related disability or infirmity as per rules.",
    documentsRequired: ["Aadhaar card", "Age proof", "Disability or medical certificate", "Income proof"],
    applyLink: "https://alimco.in/",
    rules: {
      age: ["60-69", "70-79", "80+"],
      healthCondition: ["Disability", "Needs support", "Chronic illness"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Vaya Vandana Yojana",
    category: "senior",
    benefits: "Pension scheme for senior citizens through LIC.",
    eligibility: "Senior citizens meeting scheme age and investment rules.",
    documentsRequired: ["Aadhaar card", "PAN card", "Bank details", "Age proof"],
    applyLink: "https://licindia.in/",
    rules: {
      age: ["60-69", "70-79", "80+"],
    },
    active: true,
  },
  {
    name: "National Family Benefit Scheme",
    category: "family",
    benefits: "One-time assistance to eligible families after death of primary breadwinner.",
    eligibility: "Below poverty line families as per NSAP rules.",
    documentsRequired: ["Death certificate", "Aadhaar card", "BPL proof", "Bank details"],
    applyLink: "https://nsap.nic.in/",
    rules: {
      income: ["Below 1 lakh"],
      familySize: ["3-4", "5+"],
    },
    active: true,
  },
  {
    name: "Jal Jeevan Mission",
    category: "family",
    benefits: "Tap water connection support for rural households.",
    eligibility: "Rural households as per mission implementation rules.",
    documentsRequired: ["Address proof", "Aadhaar card", "Household details"],
    applyLink: "https://jaljeevanmission.gov.in/",
    rules: {
      houseType: ["Own house", "Rented house", "No house"],
      state: ["Karnataka", "Maharashtra", "Tamil Nadu", "Telangana", "Andhra Pradesh", "Other"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Ujjwala Yojana",
    category: "family",
    benefits: "LPG connection support for eligible households.",
    eligibility: "Eligible adult women from poor households as per scheme rules.",
    documentsRequired: ["Aadhaar card", "Ration card", "Bank details", "Address proof"],
    applyLink: "https://www.pmuy.gov.in/",
    rules: {
      income: ["Below 1 lakh", "1-3 lakh"],
      familySize: ["1-2", "3-4", "5+"],
    },
    active: true,
  },
  {
    name: "Swachh Bharat Mission Household Toilet Support",
    category: "family",
    benefits: "Support for household toilet construction where eligible.",
    eligibility: "Eligible households without toilet facility as per local rules.",
    documentsRequired: ["Aadhaar card", "Address proof", "Bank details"],
    applyLink: "https://swachhbharatmission.gov.in/",
    rules: {
      houseType: ["Own house", "Rented house"],
      income: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "Samagra Shiksha",
    category: "student",
    benefits: "School education support through integrated education programme.",
    eligibility: "School students covered under state implementation plans.",
    documentsRequired: ["School ID", "Aadhaar card if required", "Address proof"],
    applyLink: "https://samagra.education.gov.in/",
    rules: {
      educationLevel: ["School"],
    },
    active: true,
  },
  {
    name: "AICTE Pragati Scholarship for Girls",
    category: "student",
    benefits: "Scholarship support for girl students in technical education.",
    eligibility: "Eligible girl students admitted to technical diploma/degree courses.",
    documentsRequired: ["Aadhaar card", "Income certificate", "Admission proof", "Bank details"],
    applyLink: "https://www.aicte-india.org/",
    rules: {
      gender: ["Female"],
      educationLevel: ["Diploma", "Graduate"],
      annualFamilyIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "National Means-cum-Merit Scholarship",
    category: "student",
    benefits: "Scholarship support for meritorious students from low-income families.",
    eligibility: "Eligible school students meeting merit and income criteria.",
    documentsRequired: ["Income certificate", "School certificate", "Marks card", "Bank details"],
    applyLink: "https://scholarships.gov.in/",
    rules: {
      educationLevel: ["School"],
      annualFamilyIncome: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "Credit Guarantee Fund Trust for Micro and Small Enterprises",
    category: "business",
    benefits: "Collateral-free credit guarantee support for eligible MSMEs.",
    eligibility: "Eligible micro and small enterprises as per CGTMSE rules.",
    documentsRequired: ["Business proof", "Bank statement", "Udyam registration", "Project details"],
    applyLink: "https://www.cgtmse.in/",
    rules: {
      loanRequired: "Yes",
      businessType: ["Shop", "Tailoring", "Food business", "Service", "Other"],
    },
    active: true,
  },
  {
    name: "Udyam Registration",
    category: "business",
    benefits: "MSME registration to access government benefits and support.",
    eligibility: "Micro, small, and medium enterprises as per MSME criteria.",
    documentsRequired: ["Aadhaar card", "PAN card", "Business details"],
    applyLink: "https://udyamregistration.gov.in/",
    rules: {
      businessType: ["Shop", "Tailoring", "Food business", "Service", "Other"],
    },
    active: true,
  },
  {
    name: "Startup India Seed Fund Scheme",
    category: "business",
    benefits: "Seed funding support for eligible startups.",
    eligibility: "DPIIT-recognized startups meeting scheme criteria.",
    documentsRequired: ["DPIIT recognition", "Business plan", "Company documents", "Bank details"],
    applyLink: "https://www.startupindia.gov.in/",
    rules: {
      loanRequired: "Yes",
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh", "Above 6 lakh"],
    },
    active: true,
  },
  {
    name: "National Livelihood Mission Self Help Group Support",
    category: "business",
    benefits: "Support for self-help groups and livelihood activities.",
    eligibility: "Eligible rural poor households and SHG members.",
    documentsRequired: ["Aadhaar card", "SHG details", "Bank details"],
    applyLink: "https://aajeevika.gov.in/",
    rules: {
      businessType: ["Food business", "Tailoring", "Service", "Other"],
      annualIncome: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
];

const expandedSchemes = [
  {
    name: "PM Kisan Maandhan Yojana",
    category: "farmer",
    benefits: "Pension support for eligible small and marginal farmers in old age.",
    eligibility: "Small and marginal farmers who meet the scheme age and contribution rules.",
    documentsRequired: ["Aadhaar card", "Bank details", "Land records", "Mobile number"],
    applyLink: "https://maandhan.in/",
    rules: {
      age: ["18-25", "26-40"],
      landSize: ["Below 1 acre", "1-5 acres"],
      annualIncome: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "National Agriculture Market e-NAM",
    category: "farmer",
    benefits: "Online market access to help farmers discover better crop prices.",
    eligibility: "Farmers selling agricultural produce in participating mandis.",
    documentsRequired: ["Aadhaar card", "Bank details", "Mobile number", "Farmer registration details"],
    applyLink: "https://www.enam.gov.in/",
    rules: {
      cropType: ["Rice", "Wheat", "Cotton", "Vegetables", "Other"],
      landSize: ["Below 1 acre", "1-5 acres", "Above 5 acres"],
    },
    active: true,
  },
  {
    name: "Rashtriya Krishi Vikas Yojana",
    category: "farmer",
    benefits: "Support for agriculture development activities through state projects.",
    eligibility: "Farmers covered under approved state agriculture projects.",
    documentsRequired: ["Aadhaar card", "Land records", "Bank details", "State agriculture registration"],
    applyLink: "https://rkvy.nic.in/",
    rules: {
      state: ["Karnataka", "Maharashtra", "Tamil Nadu", "Telangana", "Andhra Pradesh", "Other"],
      cropType: ["Rice", "Wheat", "Cotton", "Vegetables", "Other"],
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "National Food Security Mission",
    category: "farmer",
    benefits: "Support for improving production of food crops and farm practices.",
    eligibility: "Farmers growing eligible food crops under state programme guidelines.",
    documentsRequired: ["Aadhaar card", "Land records", "Crop details", "Bank details"],
    applyLink: "https://www.nfsm.gov.in/",
    rules: {
      cropType: ["Rice", "Wheat"],
      landSize: ["Below 1 acre", "1-5 acres", "Above 5 acres"],
      irrigationAvailable: ["Yes", "No"],
    },
    active: true,
  },
  {
    name: "National Mission for Sustainable Agriculture",
    category: "farmer",
    benefits: "Support for climate-resilient farming, water conservation, and sustainable agriculture.",
    eligibility: "Farmers covered under sustainable agriculture and water-use programmes.",
    documentsRequired: ["Aadhaar card", "Land records", "Bank details", "Farm details"],
    applyLink: "https://nmsa.dac.gov.in/",
    rules: {
      irrigationAvailable: ["No"],
      cropType: ["Rice", "Wheat", "Vegetables", "Other"],
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "DAY-NRLM Women Self Help Group Support",
    category: "woman",
    benefits: "Livelihood and credit support for women through self-help groups.",
    eligibility: "Women from eligible rural households and SHG members.",
    documentsRequired: ["Aadhaar card", "SHG details", "Bank details", "Income certificate"],
    applyLink: "https://aajeevika.gov.in/",
    rules: {
      occupation: ["Homemaker", "Worker", "Small business", "Farmer"],
      income: ["Below 1 lakh", "1-3 lakh"],
      maritalStatus: ["Single", "Married", "Widowed", "Divorced"],
    },
    active: true,
  },
  {
    name: "Mahila Samman Savings Certificate",
    category: "woman",
    benefits: "Small savings option for women and girls through post offices and eligible banks.",
    eligibility: "Women and girl children as per small savings scheme rules.",
    documentsRequired: ["Aadhaar card", "PAN card if required", "Photograph", "Deposit amount"],
    applyLink: "https://www.indiapost.gov.in/",
    rules: {
      age: ["18-25", "26-40", "41-60", "60+"],
      occupation: ["Homemaker", "Worker", "Small business", "Farmer", "Student"],
    },
    active: true,
  },
  {
    name: "Nari Shakti Puraskar",
    category: "woman",
    benefits: "Recognition for outstanding work towards women empowerment.",
    eligibility: "Women and institutions meeting award nomination criteria.",
    documentsRequired: ["Identity proof", "Work details", "Recommendation or nomination documents"],
    applyLink: "https://awards.gov.in/",
    rules: {
      occupation: ["Worker", "Small business", "Farmer", "Student"],
      educationLevel: ["School", "PUC/12th", "Graduate"],
    },
    active: true,
  },
  {
    name: "Support to Training and Employment Programme for Women",
    category: "woman",
    benefits: "Skill training and employment support for women.",
    eligibility: "Women needing skills and livelihood training through approved projects.",
    documentsRequired: ["Aadhaar card", "Address proof", "Income proof", "Education proof if required"],
    applyLink: "https://wcd.nic.in/",
    rules: {
      occupation: ["Homemaker", "Worker", "Student"],
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
      educationLevel: ["No formal education", "School", "PUC/12th", "Graduate"],
    },
    active: true,
  },
  {
    name: "PM Vishwakarma for Women Artisans",
    category: "woman",
    benefits: "Skill, toolkit, and credit support for eligible traditional artisans.",
    eligibility: "Women artisans and craft workers in eligible traditional trades.",
    documentsRequired: ["Aadhaar card", "Mobile number", "Bank details", "Occupation proof"],
    applyLink: "https://pmvishwakarma.gov.in/",
    rules: {
      occupation: ["Worker", "Small business"],
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "National Social Assistance Programme Senior Pension",
    category: "senior",
    benefits: "Social pension support for eligible elderly persons from poor households.",
    eligibility: "Senior citizens meeting NSAP or state social pension criteria.",
    documentsRequired: ["Aadhaar card", "Age proof", "Income certificate", "Bank details"],
    applyLink: "https://nsap.nic.in/",
    rules: {
      age: ["60-69", "70-79", "80+"],
      pensionStatus: ["Not receiving pension"],
      income: ["Below 1 lakh"],
    },
    active: true,
  },
  {
    name: "Integrated Programme for Senior Citizens",
    category: "senior",
    benefits: "Care, shelter, and support services for needy senior citizens.",
    eligibility: "Senior citizens needing care, support, or institutional services.",
    documentsRequired: ["Aadhaar card", "Age proof", "Address proof", "Health documents if available"],
    applyLink: "https://socialjustice.gov.in/",
    rules: {
      age: ["60-69", "70-79", "80+"],
      healthCondition: ["Needs support", "Chronic illness", "Disability"],
      income: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "Senior Citizens Savings Scheme",
    category: "senior",
    benefits: "Government-backed savings option for senior citizens.",
    eligibility: "Senior citizens meeting account opening and deposit rules.",
    documentsRequired: ["Aadhaar card", "PAN card", "Age proof", "Bank or post office documents"],
    applyLink: "https://www.indiapost.gov.in/",
    rules: {
      age: ["60-69", "70-79", "80+"],
      pensionStatus: ["Receiving pension", "Not receiving pension"],
    },
    active: true,
  },
  {
    name: "Elderline National Helpline for Senior Citizens",
    category: "senior",
    benefits: "Helpline support for elderly care, rescue, counselling, and information.",
    eligibility: "Senior citizens and caregivers needing support or information.",
    documentsRequired: ["Mobile number", "Basic identity details if required"],
    applyLink: "https://elderline.dosje.gov.in/",
    rules: {
      age: ["60-69", "70-79", "80+"],
      healthCondition: ["Healthy", "Chronic illness", "Disability", "Needs support"],
    },
    active: true,
  },
  {
    name: "ADIP Scheme for Persons with Disabilities",
    category: "senior",
    benefits: "Assistive devices support for eligible persons with disabilities.",
    eligibility: "Eligible persons with certified disability and income criteria.",
    documentsRequired: ["Aadhaar card", "Disability certificate", "Income certificate", "Photograph"],
    applyLink: "https://depwd.gov.in/",
    rules: {
      healthCondition: ["Disability", "Needs support"],
      income: ["Below 1 lakh", "1-3 lakh"],
    },
    active: true,
  },
  {
    name: "Ayushman Bharat Health Account",
    category: "family",
    benefits: "Digital health account to access and manage health records.",
    eligibility: "Any resident who wants a digital health ID.",
    documentsRequired: ["Aadhaar card or mobile number"],
    applyLink: "https://abha.abdm.gov.in/",
    rules: {
      familySize: ["1-2", "3-4", "5+"],
      state: ["Karnataka", "Maharashtra", "Tamil Nadu", "Telangana", "Andhra Pradesh", "Other"],
    },
    active: true,
  },
  {
    name: "PM Garib Kalyan Anna Yojana",
    category: "family",
    benefits: "Food grain support for eligible ration card households.",
    eligibility: "Eligible NFSA ration card households as per government rules.",
    documentsRequired: ["Ration card", "Aadhaar card", "Family details"],
    applyLink: "https://nfsa.gov.in/",
    rules: {
      income: ["Below 1 lakh", "1-3 lakh"],
      familySize: ["3-4", "5+"],
    },
    active: true,
  },
  {
    name: "PM Surya Ghar Muft Bijli Yojana",
    category: "family",
    benefits: "Rooftop solar subsidy support for eligible households.",
    eligibility: "Residential households meeting rooftop solar installation rules.",
    documentsRequired: ["Electricity bill", "Aadhaar card", "Bank details", "Roof ownership details"],
    applyLink: "https://pmsuryaghar.gov.in/",
    rules: {
      houseType: ["Own house"],
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh", "Above 6 lakh"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Jan Dhan Yojana",
    category: "family",
    benefits: "Basic bank account access for financial inclusion.",
    eligibility: "Unbanked individuals and families as per bank account rules.",
    documentsRequired: ["Aadhaar card", "Address proof", "Photograph"],
    applyLink: "https://pmjdy.gov.in/",
    rules: {
      income: ["Below 1 lakh", "1-3 lakh"],
      familySize: ["1-2", "3-4", "5+"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    category: "family",
    benefits: "Low-cost life insurance cover for eligible bank account holders.",
    eligibility: "Eligible savings bank account holders within scheme age rules.",
    documentsRequired: ["Bank account", "Aadhaar card", "Consent form"],
    applyLink: "https://www.jansuraksha.gov.in/",
    rules: {
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
      familySize: ["1-2", "3-4", "5+"],
    },
    active: true,
  },
  {
    name: "Pradhan Mantri Suraksha Bima Yojana",
    category: "family",
    benefits: "Low-cost accident insurance cover for eligible bank account holders.",
    eligibility: "Eligible savings bank account holders within scheme age rules.",
    documentsRequired: ["Bank account", "Aadhaar card", "Consent form"],
    applyLink: "https://www.jansuraksha.gov.in/",
    rules: {
      income: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
      familySize: ["1-2", "3-4", "5+"],
    },
    active: true,
  },
  {
    name: "PM POSHAN Mid-Day Meal Scheme",
    category: "student",
    benefits: "Nutritious cooked meal support for eligible school children.",
    eligibility: "Children studying in eligible government and aided schools.",
    documentsRequired: ["School enrollment details"],
    applyLink: "https://pmposhan.education.gov.in/",
    rules: {
      educationLevel: ["School"],
      age: ["18-25"],
      annualFamilyIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "PM YASASVI Scholarship",
    category: "student",
    benefits: "Scholarship support for eligible OBC, EBC, and DNT students.",
    eligibility: "Students meeting category, income, and education criteria.",
    documentsRequired: ["Aadhaar card", "Income certificate", "Category certificate", "School or college documents"],
    applyLink: "https://scholarships.gov.in/",
    rules: {
      casteCategory: ["OBC"],
      annualFamilyIncome: ["Below 1 lakh", "1-3 lakh"],
      educationLevel: ["School", "PUC/12th"],
    },
    active: true,
  },
  {
    name: "Central Sector Scheme of Scholarship for College and University Students",
    category: "student",
    benefits: "Scholarship support for meritorious college and university students.",
    eligibility: "Students meeting merit and family income criteria.",
    documentsRequired: ["Marks card", "Income certificate", "College admission proof", "Bank details"],
    applyLink: "https://scholarships.gov.in/",
    rules: {
      educationLevel: ["PUC/12th", "Graduate"],
      annualFamilyIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "INSPIRE Scholarship for Higher Education",
    category: "student",
    benefits: "Scholarship support for eligible students pursuing science education.",
    eligibility: "Meritorious students meeting science education and programme criteria.",
    documentsRequired: ["Marks card", "Admission proof", "Bank details", "Identity proof"],
    applyLink: "https://online-inspire.gov.in/",
    rules: {
      educationLevel: ["PUC/12th", "Graduate"],
      age: ["18-25"],
    },
    active: true,
  },
  {
    name: "National Overseas Scholarship",
    category: "student",
    benefits: "Financial support for eligible students pursuing higher studies abroad.",
    eligibility: "Eligible SC, ST, and other notified category students meeting income and admission criteria.",
    documentsRequired: ["Category certificate", "Income certificate", "Admission letter", "Passport", "Marks cards"],
    applyLink: "https://nosmsje.gov.in/",
    rules: {
      casteCategory: ["SC", "ST"],
      educationLevel: ["Graduate"],
      annualFamilyIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "ASPIRE Scheme for Rural Enterprises",
    category: "business",
    benefits: "Support for innovation and entrepreneurship in agro and rural industries.",
    eligibility: "Eligible entrepreneurs and enterprises in rural or agro-based activities.",
    documentsRequired: ["Aadhaar card", "Business plan", "Bank details", "Enterprise documents"],
    applyLink: "https://msme.gov.in/",
    rules: {
      businessType: ["Food business", "Service", "Other"],
      loanRequired: ["Yes"],
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "SFURTI Cluster Development Scheme",
    category: "business",
    benefits: "Cluster support for traditional industries and artisans.",
    eligibility: "Eligible artisan groups, clusters, and implementing agencies.",
    documentsRequired: ["Cluster details", "Identity proof", "Bank details", "Business or artisan proof"],
    applyLink: "https://sfurti.msme.gov.in/",
    rules: {
      businessType: ["Tailoring", "Food business", "Service", "Other"],
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "PM Formalisation of Micro Food Processing Enterprises",
    category: "business",
    benefits: "Credit-linked subsidy and support for micro food processing units.",
    eligibility: "Existing or new micro food processing entrepreneurs meeting scheme rules.",
    documentsRequired: ["Aadhaar card", "Business proof", "Project report", "Bank details"],
    applyLink: "https://pmfme.mofpi.gov.in/",
    rules: {
      businessType: ["Food business"],
      loanRequired: ["Yes"],
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "Prime Minister's Employment Generation Programme",
    category: "business",
    benefits: "Subsidy-linked finance for setting up micro-enterprises.",
    eligibility: "Eligible applicants starting new micro-enterprises under KVIC rules.",
    documentsRequired: ["Aadhaar card", "Project report", "Education proof", "Bank details"],
    applyLink: "https://www.kviconline.gov.in/pmegpeportal/",
    rules: {
      businessType: ["Shop", "Tailoring", "Food business", "Service", "Other"],
      loanRequired: ["Yes"],
      annualIncome: ["Below 1 lakh", "1-3 lakh", "3-6 lakh"],
    },
    active: true,
  },
  {
    name: "Stand-Up India for SC ST and Women Entrepreneurs",
    category: "business",
    benefits: "Bank loan support for eligible greenfield enterprises.",
    eligibility: "SC, ST, or women entrepreneurs starting eligible enterprises.",
    documentsRequired: ["Aadhaar card", "Caste certificate if applicable", "Business plan", "Bank details"],
    applyLink: "https://www.standupmitra.in/",
    rules: {
      businessType: ["Shop", "Tailoring", "Food business", "Service", "Other"],
      loanRequired: ["Yes"],
      annualIncome: ["1-3 lakh", "3-6 lakh", "Above 6 lakh"],
    },
    active: true,
  },
];

const allSchemes = [...schemes, ...additionalSchemes, ...expandedSchemes];

const seedDatabase = async () => {
  await connectDB();

  categories.forEach((category) => {
    category.schemeCount = allSchemes.filter((scheme) => scheme.category === category.id).length;
  });

  await Promise.all(
    categories.map((category) =>
      Category.updateOne({ id: category.id }, { $set: category }, { upsert: true })
    )
  );

  await Promise.all(
    allSchemes.map((scheme) =>
      Scheme.updateOne({ name: scheme.name }, { $set: scheme }, { upsert: true })
    )
  );

  await UserResponse.createCollection();

  console.log(`Seeded ${categories.length} categories`);
  console.log(`Seeded ${allSchemes.length} schemes`);
  console.log("Created userresponses collection");

  await mongoose.connection.close();
};

seedDatabase().catch(async (error) => {
  console.error("Database seed failed:", error.message);
  await mongoose.connection.close().catch(() => {});
  process.exit(1);
});
